
TOP=../..
.include "$(TOP)/mk/os161.config.mk"

# Just add new directories at the end of the line below.
SUBDIRS= example 
SUBDIRS= hell
SUBDIRS= time
SUBDIRS= getapid
SUBDIRS= forkYOU

.include "$(TOP)/mk/os161.subdir.mk"
